<?php
echo "<!DOCTYPE HTML>\n"; 
echo "<html lang=\"en\">\n"; 
echo "    <head>\n"; 
echo "        <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\"> \n"; 
echo "        <meta charset=\"utf-8\">\n"; 
echo "        <title>Bootply.com - Bootstrap Bootstrap 3 Admin</title>\n"; 
echo "        <meta name=\"generator\" content=\"Bootply\" />\n"; 
echo "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\n"; 
echo "        <link href=\"//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css\" rel=\"stylesheet\">\n"; 
echo "        \n"; 
echo "        <!--[if lt IE 9]>\n"; 
echo "          <script src=\"//html5shim.googlecode.com/svn/trunk/html5.js\"></script>\n"; 
echo "        <![endif]-->\n"; 
echo "        <link rel=\"shortcut icon\" href=\"/bootstrap/img/favicon.ico\">\n"; 
echo "        <link rel=\"apple-touch-icon\" href=\"/bootstrap/img/apple-touch-icon.png\">\n"; 
echo "        <link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"/bootstrap/img/apple-touch-icon-72x72.png\">\n"; 
echo "        <link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"/bootstrap/img/apple-touch-icon-114x114.png\">\n"; 
echo "    </head>\n"; 
echo "<body>\n"; 
echo "\n"; 
echo "<div class=\"jumbotron\">\n"; 
echo "  <h1>Testing</h1> \n"; 
echo "  <p>Bootstrap is the most popular HTML, CSS, and JS framework for developing responsive,\n"; 
echo "  mobile-first projects on the web.</p> \n"; 
echo "</div>\n"; 
echo "    \n"; 
echo "<div class=\"container-fluid\">\n"; 
echo "  <nav class=\"navbar navbar-default\">\n"; 
echo "  <div class=\"container-fluid\">\n"; 
echo "    <!-- Brand and toggle get grouped for better mobile display -->\n"; 
echo "    <div class=\"navbar-header\">\n"; 
echo "      <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\n"; 
echo "        <span class=\"sr-only\">Toggle navigation</span>\n"; 
echo "        <span class=\"icon-bar\"></span>\n"; 
echo "        <span class=\"icon-bar\"></span>\n"; 
echo "        <span class=\"icon-bar\"></span>\n"; 
echo "      </button>\n"; 
echo "      <a class=\"navbar-brand\" href=\"#\">InflatedBalloon</a>\n"; 
echo "    </div>\n"; 
echo "\n"; 
echo "    <!-- Collect the nav links, forms, and other content for toggling -->\n"; 
echo "    <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\n"; 
echo "      <ul class=\"nav navbar-nav\">\n"; 
echo "\n"; 
echo "       \n"; 
echo "      </ul>\n"; 
echo "      <form class=\"navbar-form navbar-left\">\n"; 
echo "          <button type=\"button\" class=\"btn btn-default\">Kandidaadid</button>\n"; 
echo "          <button type=\"button\" class=\"btn btn-default\">Erakonnad</button>\n"; 
echo "          <button type=\"button\" class=\"btn btn-default\">Tulemused</button>\n"; 
echo "      </form>\n"; 
echo "      <ul class=\"nav navbar-nav navbar-right\">\n"; 
echo "          \n"; 
echo "                 <li class=\"dropdown\">\n"; 
echo "          <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-expanded=\"false\">My Account <span class=\"caret\"></span></a>\n"; 
echo "          <ul class=\"dropdown-menu\" role=\"menu\">\n"; 
echo "            <li><a href=\"#\">Vote</a></li>\n"; 
echo "            <li><a href=\"#\">My Vote History</a></li>\n"; 
echo "            <li><a href=\"#\">My applications</a></li>\n"; 
echo "            <li class=\"divider\"></li>\n"; 
echo "            <li><a href=\"#\">Log Out</a></li>\n"; 
echo "          </ul>\n"; 
echo "        </li>\n"; 
echo "      </ul>\n"; 
echo "    </div><!-- /.navbar-collapse -->\n"; 
echo "  </div><!-- /.container-fluid -->\n"; 
echo "</nav>\n"; 
echo "</div>\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "    \n"; 
echo "<div class=\"container\">\n"; 
echo "  <div class=\"jumbotron\">\n"; 
echo "        <div class=\"product\">               \n"; 
echo "                <div class=\"product_image\">\n"; 
echo "                   <img class=\"img-responsive\" src=\"resources/card.png\" alt=\"\"/>\n"; 
echo "                </div>\n"; 
echo "             </div>\n"; 
echo "     </div>\n"; 
echo "</div>\n"; 
echo "\n"; 
echo "</body>\n"; 
echo "</html>\n"; 
echo "\n";
?>